#KERNELDIR =${KERNELSRC}

obj-m := tp2854.o tp2854_subcam.o
#obj-y := tp2854.o

#modules:
#	$(MAKE) -C $(KERNELDIR) M=$(PWD)
#
#clean:
#	rm -rf *.o *~ core .depend .*.cmd *.ko *.mod.c .tmp_versions modules.order  Module.symvers
#
#.PHONY: modules install clean
